import {
  selectPriceAndType,
  selectAreaType,
  makeSelectSlideRoutesAndPrice,
  makeSelectContentType,
  makeSelectIsSwitchable,
  selectTravellerLen,
  makeSelectBaggageData,
  makeSelectIsHaveOverweight,
  selectOverweightData,
  makeSelectSelectedOverweight,
  selectBaggageIATA,
  makeSelectSameBaggage,
  selectBaggageData,
  selectBaggagePrice,
  makeSelectSegmentIndex,
  makeSelectedBaggageData,
} from './selectors';

export const baggageSelect = {
  makeSelectSameBaggage,
  selectBaggageIATA,
  makeSelectSelectedOverweight,
  selectOverweightData,
  makeSelectIsHaveOverweight,
  makeSelectBaggageData,
  makeSelectSlideRoutesAndPrice,
  makeSelectIsSwitchable,
  makeSelectContentType,
  makeSelectSegmentIndex,
  selectTravellerLen,
  selectPriceAndType,
  selectAreaType,
  selectBaggageData,
  selectBaggagePrice,
  makeSelectedBaggageData,
};
